### ISSUE TITLE
got this while testing

### ISSUE THREAD

**Issue by bakedCouchPotato** [dirkboye/mailpw_change#5]
<type 'exceptions.ImportError'>	Python 2.7.3: /usr/local/bin/python2.7
Sun May 31 12:19:22 2015
A problem occurred in a Python script. Here is the sequence of function calls leading up to the error, in the order they occurred.

 /var/www/virtual/sbrevde/cgi-bin/changepw.py in ()
      2 import cgi
      3 import cgitb; cgitb.enable()
=>    4 import pwd, sys, os, cdb, subprocess
      5 from subprocess import check_output,Popen,PIPE
      6 from os.path import expanduser
pwd = <module 'pwd' (built-in)>, sys = <module 'sys' (built-in)>, os = <module 'os' from '/package/host/localhost/python-2.7/lib/python2.7/os.pyc'>, cdb undefined, subprocess undefined
<type 'exceptions.ImportError'>: No module named cdb 
      args = ('No module named cdb',) 
      message = 'No module named cdb'

**Comment by OldShatterhand77** [comment]
"Dependencies of Python script: python-cdb
Install on your uberspace with easy_install-2.7 python-cdb"

Obviously you forgot to install the needed dependency. Please install it and it should work!

**Comment by omeganos** [comment]
Hi,
trying to install python-cdb on uberspace and i get the following error:

>easy_install-2.7 python-cdb
>error: can't create or remove files in install directory

>The following error occurred while trying to add or remove files in the installation directory:

>    [Errno 13] Permission denied: '/package/host/localhost/python-2.7.10/lib/python2.7/site-packages/test-easy-install-2010.write-test'

>The installation directory you specified (via --install-dir, --prefix, or the distutils default setting) was:

>    /package/host/localhost/python-2.7.10/lib/python2.7/site-packages/

>Perhaps your account does not have write access to this directory?  If the
installation directory is a system-owned directory, you may need to sign in
as the administrator or "root" account.  If you do not have administrative
access to this machine, you may wish to choose a different installation
directory, preferably one that is listed in your PYTHONPATH environment
variable.

>For information on other options, you may wish to consult the
documentation at:

>  https://pythonhosted.org/setuptools/easy_install.html

>Please make the appropriate changes for your system and try again.`

is there any other way to install phyton-cdb or to change mail-Passwords?

ty
